### ISSUE TITLE
Pull in archive of old site

### ISSUE THREAD

**Issue by jc00ke** [pdxruby/pdxruby.github.io#9]
Let's pull http://pdxruby.org/old/ under this site too.

**Comment by edrex** [comment]
wget?

**Comment by jc00ke** [comment]
`wget`'ing right now

**Comment by edrex** [comment]
@jc00ke what do you think of possibly putting the old site into a separate repo and then including it via a submodule to keep the repo small? Github pages will automatically pull in the submodule.

**Comment by edrex** [comment]
If that seems ok, if you create a repo like pdx.rb-old and add me I can set it up.

**Comment by jc00ke** [comment]
Good idea, though the repo will still contain all that history... once you get it set up I may nuke it via `rebase` and a `push -f` (shh don't tell anyone!)
https://github.com/pdxruby/pdxruby.archive

**Comment by edrex** [comment]
Ok, I set up the submodule and rebased to remove the big commit, in 

https://github.com/pdxruby/pdxruby.github.io/compare/master...edrex:archive_rebase?expand=1

The diff is a bit confusing because of subsequent commits on top, but all it's really doing is removing the big commit and adding the submodule commit on top.

So yeah, if you want to force push that branch as the new master, I think nobody will notice 🤐

**Comment by edrex** [comment]
Actually hmm, I like your idea about doing it in two stages. I'll put up a regular pull request with just the submodule commit and then you can rebase/push -f after that's merged.

**Comment by edrex** [comment]
And here it is: https://github.com/pdxruby/pdxruby.github.io/pull/15

**Comment by edrex** [comment]
looks good
